// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    
    print("hellooooo");
    print(kIsWeb);
    
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaJ22Hxk7fLVWwwjAld1hldq0bXS1WrPM',
    appId: '1:877804633592:web:81f78948faad4b2cfd2a0d',
    messagingSenderId: '877804633592',
    projectId: 'socail-swap',
    authDomain: 'socail-swap.firebaseapp.com',
    storageBucket: 'socail-swap.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQmER2rr0I-eD0tKaUGXUMLpxT4ppJZSM',
    appId: '1:877804633592:android:03883b6a60c71dcefd2a0d',
    messagingSenderId: '877804633592',
    projectId: 'socail-swap',
    storageBucket: 'socail-swap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASYeenPAGVcqRJIIGYviVWe74ftx7dCRw',
    appId: '1:877804633592:ios:ee2eaeb38a38a498fd2a0d',
    messagingSenderId: '877804633592',
    projectId: 'socail-swap',
    storageBucket: 'socail-swap.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASYeenPAGVcqRJIIGYviVWe74ftx7dCRw',
    appId: '1:877804633592:ios:89b472e29e75048bfd2a0d',
    messagingSenderId: '877804633592',
    projectId: 'socail-swap',
    storageBucket: 'socail-swap.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
